
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 31.0.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        nodeExporter:
          enabled: false
        serviceAccounts:
          nodeExporter:
            create: false
        prometheus:
          additionalServiceMonitors:
          - name: "argocd-server-metrics"
            selector:
              matchLabels:
                app.kubernetes.io/component: controller
            namespaceSelector:
              matchNames:
              - argocd
            endpoints:
              - port: tcp-controller
                interval: 30s
                path: /metrics
                scheme: http